name: Deploy Laravel to Shared Hosting

on:
  push:
    branches: [ main ]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4' # Sesuaikan dengan versi PHP di hostingmu
        extensions: mbstring, xml, ctype, iconv, intl

    # - name: Install Dependencies
    #   run: |
    #     composer install --no-ansi --no-dev --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader

    # -------------------------------------------------------------
    # STEP 1: Deploy Core Laravel ke folder 'backend' di dalam subdomain
    # -------------------------------------------------------------
    - name: Deploy Backend Core
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }} # kitfya@kursor-nyasar.kitfya.web.id
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./backend/kursor_nyasar/ # Akan terbuat di dalam folder subdomain
        exclude: |
          **/.git*
          **/node_modules/**
          **/tests/**
          public/**

    # -------------------------------------------------------------
    # STEP 2: Deploy isi folder 'public' langsung ke root FTP (Subdomain)
    # -------------------------------------------------------------
    - name: Deploy Public to Subdomain Folder
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
        server-dir: ./kursor-nyasar.kitfya.web.id/ # Langsung ditaruh di root FTP karena FTP-mu sudah mengarah ke subdomain
        port: 21
        exclude: |
          **/.git/**
